sudo: required
services:
  - docker

before_install:
  - docker build -t andiausrust/react_example_app -f Dockerfile.dev .

script:
  - docker run andiausrust/react_example_app npm run test -- --coverage
